name: Test Build  
on: 
  pull_request:
    branches: [ dev, github-actions ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    name: Running NPM Build
    steps:
      - uses: actions/checkout@v2    
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.x'

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

      # - run: 'pip install -r requirements.txt'
      # - run: 'python -m pip install --requirement requirements.txt' # worked but took ~ 14 minutes
      - name: Install Python requirements
        run: |
          pip install --upgrade --upgrade-strategy eager -r requirements.txt -e .

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run update-data
      - run: npm run build
