name: Test Build  
on: 
  pull_request:
    branches: [ dev ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    name: Running NPM Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with: 
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci

      - run: npm run update-data
      - run: npm run build
